version: "3.5"

services:
  php:    
    build:      
      context: ./.docker/php56httpd/
    environment:
      XDEBUG_RPORT: 9200
      XDEBUG_IDEKEY: VSCODE
      PHP_ROOT_DIR: /usr/local/etc
    volumes:
      - ./src-code/:/var/www/html/
    working_dir: /var/www/html/
